### ISSUE TITLE
Incompatibility with upcoming version 2.4.1 of FBP

### ISSUE THREAD

**Issue by TominoCZ** [Phylogeny/ProportionalDestructionParticles#1]
I renamed every field, method and label related to the animation/particle Exceptions. I don't know why I couldn't find the right word for this feature... so I renamed it to a Blacklist.

About the incompatibility.. 
I destroyed a block and my game crashed because your mod is looking for a specifically named method which will be renamed in the upcoming version 2.4.1 of FBP.

Here's the crashlog:
https://pastebin.com/kwHd7gKp

Keep this 'issue' as a note for the future versions of your mod.
You can check how I renamed the methods here: https://github.com/TominoCZ/FancyBlockParticles/blob/master/src_1.12.x/main/java/com/TominoCZ/FBP/FBP.java#L214

**Comment by Phylogeny** [comment]
Yeah, no problem. Thanks for the heads up.

**Comment by Phylogeny** [comment]
Alright, I've just reproduced the crash without the change I just made, then confirmed that the change fixes it inside/outside the dev environment.

**Comment by Phylogeny** [comment]
This is now fixed in v1.2.2
