### ISSUE TITLE
Crash with loading world

### ISSUE THREAD

**Issue by SeanChengN** [Phylogeny/ProportionalDestructionParticles#3]
**Describe the bug**
Use FancyBlockParticles and ProportionalDestructionParticles.

**Crash report**
https://pastebin.com/ehxja53X
https://pastebin.com/NDwped7Y

**To Reproduce**
Just loading a world.

- Mod Version: 1.2.1
- Forge: 14.23.5.2768
- FBP: 2.4.1

**Comment by Phylogeny** [comment]
Duplicate of #1 
A new build will be released shortly.

**Comment by SeanChengN** [comment]
Oh, Sorry
