### ISSUE TITLE
Grey particles with the Leaves block and others

### ISSUE THREAD

**Issue by TominoCZ** [Phylogeny/ProportionalDestructionParticles#4]
![2018-10-27_12 47 49](https://user-images.githubusercontent.com/24359011/47603037-ad6b5c80-d9e6-11e8-92fd-372bf1346991.png)

This also happens with grass and other blocks that have a color multiplier for particles.
While looking at your code, I compared the 2 ParticleManagers and I noticed one thing that is actually quite important :D

In ParticleManagerMod, you call `.setBlockPos(pos)` when you create the new particle ([here](https://github.com/Phylogeny/ProportionalDestructionParticles/blob/1.12.2/src/main/java/phylogeny/proportionaldestructionparticles/ParticleManagerMod.java#L180)), but you don't in FBPParticleManagerMod ([here](https://github.com/Phylogeny/ProportionalDestructionParticles/blob/1.12.2/src/main/java/phylogeny/proportionaldestructionparticles/FBPParticleManagerMod.java#L76)).

The method `.setBlockPos(pos)` actually does't only set a private position variable in the particle, but it also applies the color multiplier of the block to the color channels of the particle (so that leaf particles aren't grey :D).

I actually made a similar mistake in my mod in versions 2.4.0 and older, not calling this method.. But fixed it in the new version 2.4.1.

I overrode [`.setBlockPos(pos)`](https://github.com/TominoCZ/FancyBlockParticles/blob/master/src_1.12.x/main/java/com/TominoCZ/FBP/particle/FBPParticleDigging.java#L224) in FBPParticleDigging in 2.4.1 (so that it returns FBPParticleDigging and not ParticleDigging).

**Comment by Phylogeny** [comment]
Thanks! A new build will be released ASAP.

**Comment by Phylogeny** [comment]
This is now fixed in v1.2.3
